fix/overflow-in-sci-clubs-card
Solvro/mobile-topwr pull request #232
Opened 2024-09-25 12:28 UTC by TTomaszPWR

2024-09-25 22:34 UTC, simon-the-shark requested changes
sorry to say this but I don't think this is the way we want to handle this

<img width="287" alt="Zrzut ekranu 2024-09-26 o 00 33 38" src="https://github.com/user-attachments/assets/09240a05-d472-4ff1-ba56-6b6a49623803">

5 lines look much better but it has problems in few edge cases I agree. We can discuss how we want to handle that

2024-09-25 23:26 UTC, TTomaszPWR commented
> sorry to say this but I don't think this is the way we want to handle this
> 
> <img width="287" alt="Zrzut ekranu 2024-09-26 o 00 33 38" src="https://github.com/user-attachments/assets/09240a05-d472-4ff1-ba56-6b6a49623803">
> 
> 5 lines look much better but it has problems in few edge cases I agree. We can discuss how we want to handle that

Hmm, we can limit lines for science club name. I think it is a good idea. What do you think @simon-the-shark ?

2024-09-26 09:54 UTC, mikolaj-jalocha commented
> > sorry to say this but I don't think this is the way we want to handle this
> > <img alt="Zrzut ekranu 2024-09-26 o 00 33 38" width="287" src="https://private-user-images.githubusercontent.com/28555148/370914056-09240a05-d472-4ff1-ba56-6b6a49623803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQ2MjIsIm5iZiI6MTcyNzM0NDMyMiwicGF0aCI6Ii8yODU1NTE0OC8zNzA5MTQwNTYtMDkyNDBhMDUtZDQ3Mi00ZmYxLWJhNTYtNmI2YTQ5NjIzODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Y2VhMWYyM2FkZDQ3MTRiZGQ4N2IwMjAwYzVjY2Y4ZTEzYmY1NWY5ZDVjM2RkNjRhMWQ4ZDg5MWFjYTVjNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.edRWGC9QmOJIZ6AvsY67GGhsn0zCzAVDOJymF7RWEC4">
> > 5 lines look much better but it has problems in few edge cases I agree. We can discuss how we want to handle that
> 
> Hmm, we can limit lines for science club name. I think it is a good idea. What do you think @simon-the-shark ?

I'm not sure what's the exact problem but it's long names of organizations I suppose. I'd think about some kind of scalling long names. Imo they should be visible. Similar thing was done at home's screen section regarding sci clubs. You can check the solution there, maybe it'd suit for this as well.

2024-09-26 10:09 UTC, TTomaszPWR commented
> > > sorry to say this but I don't think this is the way we want to handle this
> > > <img alt="Zrzut ekranu 2024-09-26 o 00 33 38" width="287" src="https://private-user-images.githubusercontent.com/28555148/370914056-09240a05-d472-4ff1-ba56-6b6a49623803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDQ2MjIsIm5iZiI6MTcyNzM0NDMyMiwicGF0aCI6Ii8yODU1NTE0OC8zNzA5MTQwNTYtMDkyNDBhMDUtZDQ3Mi00ZmYxLWJhNTYtNmI2YTQ5NjIzODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA5NTIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Y2VhMWYyM2FkZDQ3MTRiZGQ4N2IwMjAwYzVjY2Y4ZTEzYmY1NWY5ZDVjM2RkNjRhMWQ4ZDg5MWFjYTVjNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.edRWGC9QmOJIZ6AvsY67GGhsn0zCzAVDOJymF7RWEC4">
> > > 5 lines look much better but it has problems in few edge cases I agree. We can discuss how we want to handle that
> > 
> > 
> > Hmm, we can limit lines for science club name. I think it is a good idea. What do you think @simon-the-shark ?
> 
> I'm not sure what's the exact problem but it's long names of organizations I suppose. I'd think about some kind of scalling long names. Imo they should be visible. Similar thing was done at home's screen section regarding sci clubs. You can check the solution there, maybe it'd suit for this as well.

That's sounds better. I'll do it.

2024-09-29 18:55 UTC, TTomaszPWR commented
After many attempts to auto-size text. I've decided to use pub dev library.

2024-09-29 21:21 UTC, simon-the-shark commented on lib/features/science_clubs_view/widgets/ensure_visible_tags.dart
> +            AutoSizeText.rich(
its' actually a real funny combination that we do calculate the max lines with our logic and then apply scaling down but the results looks pretty ok

2024-09-29 21:21 UTC, simon-the-shark approved these changes

2024-09-29 21:22 UTC, simon-the-shark commented
I'll maybe try to limit department to 1 line too - maybe the tags will be better looking. But merging this for now

2024-09-29 21:23 UTC, merged