feature: add dates to guide
Solvro/mobile-topwr pull request #308
Opened 2024-10-11 13:50 UTC by kamilfedio

Okay, I added dates
 - last updated 
 - created
 to every guide on detail's page. I think extracting the newest date on modified and created from all questions faq's. If you think there is the better option such us dates under each faq let me know!

ss's:
<img width="271" alt="image" src="https://github.com/user-attachments/assets/251de96f-3e3b-40ff-853e-3df337d899e8">

2024-10-14 18:26 UTC, mikolaj-jalocha requested changes
First, I apologize for such a long reply time. 

Few minor suggestions of mine. 

In terms of where the update should be place, I thought about upper section of the article . In small print just below main cover? @simon-the-shark  @wkrzos, wdyt?  

At many eg. news sites such convention is adopted. Date of publication and date of actualization is displayed just below main photo in small print (presumably for users who might wonder if the article is worth reading mainly because of expiration :-) )

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/features/guide_detail_view/guide_detail_view.dart
> +                      "${context.localize.created_at} ${context.getTheLatesCreatedDateGuide(questions: value.questions) ?? context.localize.not_date_available}",
When there's not date available I'd show just blank space

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/features/guide_detail_view/guide_detail_view.dart
> +                      "${context.localize.last_modified} ${context.getTheLatesUpdatedDateGuide(questions: value.questions) ?? context.localize.not_date_available}",
Same here - blank space

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/features/guide_detail_view/utils/get_the_latest_date.dart
> +extension GetTheLatestDateGuide on BuildContext {
Please, check in some other place naming convention for extensions

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/features/guide_detail_view/utils/get_the_latest_date.dart
> +        .reduce((a, b) => a.isAfter(b) ? a : b);
I'm not sure, but I recall we have some extension that quite nicely filters nulls. It is called where not null or sth like that.
I'm not sure thought if it'd fit in this scenario but def worth checking ;)

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/features/guide_detail_view/utils/get_the_latest_date.dart
> +    final DateTime? newestDate = questions
Same here.

2024-10-14 18:26 UTC, mikolaj-jalocha commented on lib/l10n/app_pl.arb
> +  "last_modified": "Ostatnia modyfikacja",
I'd say "Ostatnia aktualizacja"

2024-10-14 20:58 UTC, kamilfedio commented
Okay I changed but there is an error with code analysis and I can't find him :/

2024-10-14 20:58 UTC, mikolaj-jalocha commented
> Okay I changed but there is an error with code analysis and I can't find him :/

Don't worry. Known issue

2024-10-15 08:35 UTC, mikolaj-jalocha approved these changes
LGTM!

2024-10-15 08:36 UTC, merged