425 feat add send your idea link at guide tile
Solvro/mobile-topwr pull request #459
Opened 2024-12-01 14:52 UTC by Rejfi

Add "Share your idea" mechanism

2024-12-01 15:24 UTC, kamilfedio commented
I think I am not person to review this so I added @mikolaj-jalocha :D

2024-12-01 20:11 UTC, mikolaj-jalocha requested changes
Please see the comments

2024-12-01 20:11 UTC, mikolaj-jalocha commented on lib/features/guide_view/guide_view.dart
> +    return Padding(
do we need this padding?

2024-12-01 20:11 UTC, mikolaj-jalocha commented on lib/features/guide_view/guide_view.dart
> +        subtitle: context.localize.guide_ideas_info,
Is some kind of mark (that following text's url) clearly visible?

2024-12-01 20:17 UTC, mikolaj-jalocha commented on lib/features/guide_view/guide_view.dart
> +    path: "kn.solvro@pwr.edu.pl",
email path

2024-12-01 20:17 UTC, mikolaj-jalocha commented on lib/features/guide_view/guide_view.dart
> +    query: "subject=Pomysł na rozwój ToPWR",
query

2024-12-04 21:41 UTC, simon-the-shark approved these changes
LGTM

2024-12-04 21:41 UTC, merged